version: '2.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php_service
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: 'app'
      SERVICE_TAGS: 'dev'
    working_dir: /var/www/html
    volumes:
      - ./www/html/:/var/www/html/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ./www/html/:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'secret'
      SERVICE_TAGS: 'dev'
      SERVICE_NAME: 'mysql'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
